export enum SERIALIZATION_GROUP {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
}
export const ADMIN_ONLY_GROUP = [SERIALIZATION_GROUP.ADMIN];
export const CUSTOMER_ONLY_GROUP = [SERIALIZATION_GROUP.CUSTOMER];
export const ALL_GROUP = [
  SERIALIZATION_GROUP.ADMIN,
  SERIALIZATION_GROUP.CUSTOMER,
];
